trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_SERVICE_CONNECTION: 'AWS-Pipeline'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    # If you have any Python dependencies, install them here
    # For example: pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.11'

- script: |
    cd S3
    terraform init
  displayName: 'Terraform Init'

- script: |
    cd S3
    terraform validate
  displayName: 'Terraform Validate'

- script: |
    cd S3
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: |
    cd S3
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
