trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_SERVICE_CONNECTION: 'github.com_ashishmca86@gmail.com'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    # If you have any Python dependencies, install them here
    # For example: pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.11'

- task: UseAWSCLI@1
  inputs:
    awsCredentials: $(AWS_SERVICE_CONNECTION)

- script: |
    echo "Initializing Terraform..."
    terraform init
  displayName: 'Terraform Init'

- script: |
    echo "Validating Terraform configuration..."
    terraform validate
  displayName: 'Terraform Validate'

- script: |
    echo "Creating Terraform plan..."
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: |
    echo "Applying Terraform plan..."
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
